/*
 * This source file was generated by the Gradle 'init' task
 */
package appdatabase;

import javafx.application.Application;

public class Main {

    private Main() {

    }

    public static void main(String[] args) {
        Application.launch(View.class);
    }
}
